//! Generated Protocol Buffers / gRPC code for the Keeplin service.
//!
//! The Rust source code in this module is produced at compile time by `tonic-build`
//! (see `build.rs`) from `proto/keeplin.proto`. It is written to Cargo's `OUT_DIR`
//! and spliced in here via `tonic::include_proto!`.
//!
//! Do not edit this file manually — any changes would be overwritten on the next
//! `cargo build` run. To change the gRPC API, edit `proto/keeplin.proto` instead.

/// All types and traits generated from `keeplin.proto` live in this module.
///
/// Notable exports:
/// - `keeplin::Note`, `keeplin::Notebook`, `keeplin::Tag`, `keeplin::Resource` —
///   protobuf message structs.
/// - `keeplin::keeplin_service_server::KeeplinService` — the async trait that
///   `src/server.rs` implements.
/// - `keeplin::keeplin_service_server::KeeplinServiceServer` — the tonic service
///   wrapper registered with the gRPC server in `src/main.rs`.
/// - `keeplin::SyncProgress`, `keeplin::sync_progress::Stage` — types used in the
///   server-streaming `Sync` RPC.
#[allow(
    // The generated code contains fields and methods that the daemon does not use
    // directly (e.g. client stubs generated by build_client(true)).
    dead_code,
    // The generated code does not follow the same formatting/style rules as
    // hand-written Rust; suppressing clippy here avoids noise in CI.
    clippy::all
)]
pub mod keeplin {
    tonic::include_proto!("keeplin");
}
